### ISSUE TITLE
Instructions how to clear the database

### ISSUE THREAD

**Issue by sheepsy90** [epidemicsound/fullstack-take-home-assignment#3]
It would be good to note in the instructions that deleting the data/db folder is necessary to reset the db to it's initial value in case someone screws up.

**Comment by rootart** [comment]
@sheepsy90 thanks a lot for bringing this topic. You should be able to clear the database state using Django's `flush` command https://docs.djangoproject.com/en/4.0/ref/django-admin/#flush without the need to manually delete the database. 
We will consider adding more details to the docs and don't hesitate to contact your hiring manager if you face any other issue with the project or assignment.
