### ISSUE TITLE
Rename repo to something more specific

### ISSUE THREAD

**Issue by dakl** [epidemicsound/fullstack-take-home-assignment#6]
Atm the repo has a very generic name that begs one to ask who this is for. Changing to something like "fullstack-take-home-assignment" both makes this more clear and also acknowledges that multiple teams have take-home assignments.

**Comment by dakl** [comment]
bump

**Comment by JoarLeth** [comment]
Good point, maybe we should include python and react in the name as well so that we don't have to rename it again if we add a Kotlin version of this. But then the name would get very long 🤔 Perhaps "take-home" isn't an essential part of the name, what do you think?

**Comment by rootart** [comment]
@dakl we renamed repository as you suggested, many thanks!
